config/routes.rb
Rails.application.routes.draw do
 

  get 'registrations/index'

  get 'registrations/new'

  get 'registrations/create'

  ActiveAdmin.routes(self)
  get 'welcome/index'

  scope "(:locale)" do
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  resources :sessions

  root 'store#index'

end

resources :admins

   

end

app/models/cart.rb
class Cart < ActiveRecord::Base

	has_many :line_items ,  dependent: :destroy
	has_many :products, :through => :line_items


	def total_price
		line_items.to_a.sum{|item| item.total_price}	
	end
	
	def total_cart_price
		total_price = 0 
		self.line_items.includes(:product).each do |line_item| 
			total_price += line_item.quantity.to_i * line_item.product.price.to_f
		end
		total_price
	end 
	# def add_quantity(product_id)
	# 	puts "hello i am here"
	# 	current_item = line_items.find_by_product_id(product_id) 
	# 	if current_item
	# 	    current_item.quantity=current_item.quantity.to_i+1
	# 	else
	# 	    current_item = line_items.build(product_id: product_id)
	# 	end
	# 	current_item
	# end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 
 before_action :set_cart, only: [:show, :edit, :update, :destroy]

 rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
 
  
    
def record_not_found
         flash[:notice] = "Post successfully created"
      render file: "public/404.html", status: 404
    end

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)
    

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_url,
      notice: 'Your cart is empty' }
      format.js 
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
    
    
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
- unless @cart.line_items.empty?
  %h2.cart_title
    Your Pragmatic Cart
  %table.table
    = render (@cart.line_items)
    %tr.total_line
      %td
        Total
      %td.total_cell
        = number_to_currency(@cart.total_price, :unit => "$" )
  = button_to 'Empty Cart', @cart, method: :delete, data: { confirm: 'Are you sure?'} ,:remote =>true  ,  :id => "button"
  = button_to 'checkout', {controller: "orders",action: "new"} ,method: :get

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
          <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>
       <ul>
            <% @cart.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
$(".cart_display").hide();

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>
<%= render 'form' %>
<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p> id="notice"><%= notice %></p>
<h1>Listing Carts</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>
<%= render 'form' %>
<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
 <% end %>
<%= render @cart %>